# Prometheus Configuration for Nova Universe Production Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'nova-universe-prod'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules for alerting
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Nova Universe API Server
  - job_name: 'nova-api'
    static_configs:
      - targets: ['nova-api:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  # Nova Core Admin Interface
  - job_name: 'nova-core'
    static_configs:
      - targets: ['nova-core:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Nova Orbit End-User Portal
  - job_name: 'nova-orbit'
    static_configs:
      - targets: ['nova-orbit:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s

  # Nginx Reverse Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

# Recording rules for performance optimization
recording_rules:
  - name: nova_universe_rules
    rules:
      # API Request Rate
      - record: nova:api_request_rate_5m
        expr: rate(http_requests_total{job="nova-api"}[5m])
      
      # API Error Rate
      - record: nova:api_error_rate_5m
        expr: rate(http_requests_total{job="nova-api",status=~"5.."}[5m]) / rate(http_requests_total{job="nova-api"}[5m])
      
      # Database Connection Pool Usage
      - record: nova:db_pool_usage
        expr: (postgres_active_connections / postgres_max_connections) * 100
      
      # Memory Usage Percentage
      - record: nova:memory_usage_percent
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
      
      # Disk Usage Percentage
      - record: nova:disk_usage_percent
        expr: (1 - (node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100
