name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: nova_admin
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nova_universe
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U nova_admin -d nova_universe"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Prepare test environment
        run: |
          for dir in apps/api apps/core/nova-core apps/comms/nova-comms; do
            cp .env.example "$dir/.env"
            {
              echo DATABASE_URL=postgresql://nova_admin:postgres@localhost:5432/nova_universe
              echo POSTGRES_USER=nova_admin
              echo POSTGRES_PASSWORD=postgres
              echo POSTGRES_DB=nova_universe
              echo MONGO_ENABLED=false
            } >> "$dir/.env"
          done
      - name: Lint
        run: pnpm -r lint
      - name: Test
        run: pnpm -r test
