name: Test

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - name: Start test environment (integration)
        run: |
          chmod +x ./setup-test-env.sh
          ./setup-test-env.sh integration
      - run: pnpm run test:ci
        env:
          TEST_API_URL: http://localhost:4102
